
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PHD
 */
public class StartNewEngine extends javax.swing.JFrame {

    /**
     * Creates new form StartNewEngine
     */
    public StartNewEngine() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setTitle("Start the Maintenance of New Engine.");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Enter Serial Number");

        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Start the Maintenance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Maintenance Status...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
                            JOptionPane.showMessageDialog(this, "Please Enter Unique Serial Number");
        }
        else{
            jLabel2.setText("Loading Hour Routines..");
            jTextField1.setEditable(false);
            System.out.println(jTextField1.getText());
                try{

        Connect ca = new Connect();
        Connection cn = ca.getConnection();
        PreparedStatement psc = null;
        ResultSet rsc = null;
        Statement s = null,sc=null;
        
        String q = "select * from Hour_Group_Level_Mapping ORDER BY Hours_Maintenance";
        sc=cn.createStatement();
        rsc = sc.executeQuery(q);

            while(rsc.next())
            {
                String insGrp = rsc.getString("Inspection_Groups");
                int hrMaint = rsc.getInt("Hours_Maintenance");
//                System.out.println(insGrp+"   "+hrMaint);
                jLabel2.setText("Loading Group "+insGrp+"  -  "+hrMaint);
                s=cn.createStatement();
                //s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Ins_Group,Technician_Name,Status)values('" +jTextField1.getText()+ "','" +hrMaint+ "','" +insGrp+ "','-','Incomplete')");
                s.close();
                
                PreparedStatement psc1 = null;
                ResultSet rsc1 = null;
                Statement s1 = null,sc1=null;

                String q1 = "select Location from Group_Inspection where Group_Category = ?";
                psc1=cn.prepareStatement(q1);
                psc1.setString(1,insGrp);
                rsc1 = psc1.executeQuery();
                while(rsc1.next())
                {
                s1=cn.createStatement();
                s1.execute("insert into Inner_System_Status(Serial_Num,Hours_Eng,Group_Name,System_Name,Technician_Name,Status)values('" +jTextField1.getText()+ "','" +hrMaint+ "','" +insGrp+ "','" +rsc1.getString("Location")+ "','-','Incomplete')");
                s1.close();
                    //System.out.println("          "+insGrp+"    "+rsc1.getString("Location"));
                }
            }
/*        s=cn.createStatement();
        s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Technician_Name,Status)values('" +jTextField1.getText()+ "','125','-','Incomplete')");
        s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Technician_Name,Status)values('" +jTextField1.getText()+ "','500','-','Incomplete')");
        s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Technician_Name,Status)values('" +jTextField1.getText()+ "','1500','-','Incomplete')");
        s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Technician_Name,Status)values('" +jTextField1.getText()+ "','3000','-','Incomplete')");
        s.execute("insert into Maintenance_Tracking(Serial_Num,Hours_Track,Technician_Name,Status)values('" +jTextField1.getText()+ "','20000','-','Incomplete')");
  */      System.out.println("Tracking completed.");
        
        s.close();
        //Starting Level - 1 Form Hierarchy for 3000 and 20000 Hours.
        //For 3000 Hours.
        Maintenence_3000 m3= new Maintenence_3000("abcxdijfskdf");
        //m3.createTemplate_3000(jTextField1.getText());
        System.out.println("3000 Completed");
        jLabel2.setText("Loading Data For new Maintenance..");
        //For 20000 Hours.
        Maintenance_2000 m20k = new Maintenance_2000("Fake Value");
        //m20k.createTemplate_20000(jTextField1.getText());
        jLabel2.setText("Loading Data Sheets for new Maintenance..");
        this.dispose();
                }catch(SQLException sds){
                    sds.printStackTrace();
                }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartNewEngine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartNewEngine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartNewEngine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartNewEngine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartNewEngine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
